### ISSUE TITLE
Getting an empty college name in getCollegesList

### ISSUE THREAD

**Issue by hidacow** [ENDsoft233/shu-course-number-parser#3]
I noticed when using this function, I will get a college with an empty name, which stands for all colleges. Is this intended or not?
For example, in the project `shu-scheduling-helper`, I get the following:
![image](https://github.com/shuosc/shu-course-number-parser/assets/68262945/f7315ad9-4a92-48ae-9de8-8760e089cca7)
Which results in:
![image](https://github.com/shuosc/shu-course-number-parser/assets/68262945/699e1dc2-53a0-4157-b3d0-1437236be54d)
Should the fix (removing the empty college) be done in this project?

**Comment by BH4HPA** [comment]
是故意的设计。

https://github.com/shuosc/shu-course-number-parser/blob/e9c2dbd9f2ce5b0c31138f2115e4136c5937a3d3/src/types/majors.ts#L263

形如 `程序设计(C语言) (00864088)` 这样的课程由校级组织开设，课程号以 `00` 开头，3~4 位指示具体的校级组织，如 `0086` 指示由校级组织 `计算中心` 开设；为了使解析出的课程属性名更简短，故意删去了 `00` 的 `name` 字段，使得导出结果可由 `上海大学计算中心` 缩减为 `计算中心`，保持和其他以学院开头的解析结果的一致性。

**Comment by hidacow** [comment]
Thank you. I will close this issue.
